### ISSUE TITLE
Unable to get information about battle tags with a four digit discriminator

### ISSUE THREAD

**Issue by newtykins** [haskaalo/overwatch-api#3]
I am unable to get information about users with battle tags with a four-digit discriminator. An example, I tried using owapi to get information about Epzz#2845 and various other users with four-digit discriminators but none of them worked. 

Error:
![image](https://user-images.githubusercontent.com/19301186/62963654-53af1400-bdf9-11e9-9c73-27ad79e17501.png)

Code in question:
![image](https://user-images.githubusercontent.com/19301186/62963676-61649980-bdf9-11e9-8ffc-0be8a3315f49.png)

**Comment by jsmiith** [comment]
This repository is relatively dead. I'll just find another package that works.

**Comment by haskaalo** [comment]
Hi!

I'm going to look into it.

**Comment by jsmiith** [comment]
Oh thanks c:

**Comment by haskaalo** [comment]
@newtykins Even though this issue is from 2 years ago lol, I just want to notice you that this has been fixed in the newest release 2.1.0
